--- 
- hosts: all
  user: root
  tasks: 
  - group: 
      name: devops
      state: present
  - name: Create devops user with admin privileges

    user:
      name: devops
      comment: "devops user"
      uid: 2001
      group: devops
  - name: install htop package
    action: apt name=htop state=present update_cache=yes
- hosts: www
  user: root
  tasks: 
  - name: add nginx official repository
    apt_repository:
      repo: 'deb http://nginx.org/packages/ubuntu/ lucid nginx'
  - name: install nginx web server and ensure its at the latest version
    apt:
      name: nginx
      state: latest
  - name: start nginx service
    service:
      name: nginx
      state: started