---
- name: install Check_mk
  hosts: testsv
  remote_user: root

  tasks:
  - name: Install the latest version of EPEL-RELEASE
    yum:
      name: epel-release
      state: latest
  - name: Download Check_mk.rpm for centos 7
    get_url:
      url: https://mathias-kettner.de/support/1.5.0p13/check-mk-raw-1.5.0p13-el7-38.x86_64.rpm
      dest: /opt/setup
  - name: Install Check_mk rpm from file download
    yum:
      name: /opt/setup/check-mk-raw-1.5.0p13-el7-38.x86_64.rpm
      state: present
      